name: CD - Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH & redeploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p ~/app
            cd ~/app
            if [ ! -d ".git" ]; then
              git clone https://github.com/Chanderkant11/2212357-devops-project.git .
            else
              git fetch --all
              git reset --hard origin/main
            fi
            sudo docker-compose down || true
            sudo docker-compose up -d --build
