name: CD - Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH & redeploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Automatically install Docker if it is missing
            if ! command -v docker &> /dev/null; then
              sudo yum update -y
              sudo yum install -y docker
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker ec2-user
            fi
            
            # Setup application directory
            mkdir -p ~/app
            cd ~/app
            
            if [ ! -d ".git" ]; then
              git clone https://github.com/Chanderkant11/2212357-devops-project.git .
            else
              git fetch --all
              git reset --hard origin/main
            fi
            
            # Run application using native docker builders
            sudo docker stop web-app || true
            sudo docker rm web-app || true
            sudo docker build -t fastapi-app .
            sudo docker run -d --name web-app -p 8000:8000 fastapi-app
